on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG.MODEL: llama-3.1-70b-versatile
          CONFIG.MODEL_TURBO: llama-3.1-70b-versatile
          CONFIG.FALLBACK_MODELS: 'groq/llama-3.1-70b-versatile'
          GROQ.KEY: ${{ secrets.GROQ_KEY }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: >- 
            Chuyển câu trả lời sang tiếng Việt.
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: >- 
            Tiêu đề phải bao gồm một tiền tố từ mẫu commitlint như feat:, chore:, test:, fix:, ci:, hoặc docs:... 
            Tiêu đề phải là tiếng anh ngắn gọn và viết thường toàn bộ câu.
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: >-
            Chuyển câu trả lời sang tiếng Việt.
          PR_DESCRIPTION.GENERATE_AI_TITLE: true
